version: 2.1

parameters:
  specgen-version:
    type: string
    default: 2.0.404

jobs:
  generate-commit:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - install-specgen
      - run:
          name: Generate models
          command: |
            rm -R -- ./models/*/
            ./specgen models-java --spec-file ./models/spec.yaml --generate-path ./models/java
            ./specgen models-go --spec-file ./models/spec.yaml --generate-path ./models/go
      - run:
          name: Remove specgen
          command: rm specgen
      - tree:
          path: ./models
      - run:
          name: Commit changes
          command: |
            git add --all
            if [[ `git status --porcelain` ]]; then
              git config --global user.email "vladimir.sapronov@gmail.com"
              git config --global user.name "vsapronov"
              git commit -m "[skip ci] Generated code with specgen <<pipeline.parameters.specgen-version>>"
              git remote set-url origin https://vsapronov:$GITHUB_TOKEN@github.com/specgen-io/generated-code.git
              git push
            else
              echo "No changes detected - nothing to commit"
            fi

commands:
  tree:
    parameters:
      path:
        type: string
        default: .
    steps:
      - run:
          name: Print flie system tree
          command: find <<parameters.path>> | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
  install-specgen:
    steps:
      - run:
          name: Install specgen
          command: |
            curl -L https://github.com/specgen-io/specgen/releases/download/v<<pipeline.parameters.specgen-version>>/specgen_linux_amd64.zip > specgen_linux_amd64.zip
            unzip -o specgen_linux_amd64.zip
            rm specgen_linux_amd64.zip

workflows:
  generate-commit:
    jobs:
      - generate-commit:
          context: specgen