version: 2.1

parameters:
  specgen-version:
    type: string
    default: 2.1.1458
  specgen-version-major:
    type: string
    default: v2

jobs:
  generated-code:
    docker:
      - image: cimg/go:1.16.4
    steps:
      - checkout
      - run:
          name: Install specgen
          command: |
            go install github.com/specgen-io/specgen/<<pipeline.parameters.specgen-version-major>>@v<< pipeline.parameters.specgen-version >>
            specgen --help
      - run:
          name: Clean code
          command: |
            rm -R -- ./models/*/
            rm -R -- ./clients/*/
            rm -R -- ./services/*/
      - gen-models:
          path: models/openapi
          specgen: openapi --spec-file ./spec.yaml --out-file ./swagger.yaml
      - gen-models:
          path: models/java-jackson
          specgen: models-java --jsonlib jackson --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/java-moshi
          specgen: models-java --jsonlib moshi --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/kotlin-jackson
          specgen: models-kotlin --jsonlib jackson --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/go
          specgen: models-go --spec-file ./spec.yaml --module-name test-models --generate-path .
      - gen-models:
          path: models/ruby
          specgen: models-ruby --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/scala-circe
          specgen: models-scala --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/ts-iots
          specgen: models-ts --validation io-ts --spec-file ./spec.yaml --generate-path .
      - gen-models:
          path: models/ts-superstruct
          specgen: models-ts --validation superstruct --spec-file ./spec.yaml --generate-path .

      - gen-client:
          path: clients/openapi
          specgen: openapi --spec-file ./spec.yaml --out-file ./swagger.yaml
      - gen-client:
          path: clients/java-okhttp-jackson
          specgen: client-java --jsonlib jackson --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/java-okhttp-moshi
          specgen: client-java --jsonlib moshi --spec-file ./spec.yaml --generate-path .    
      - gen-client:
          path: clients/kotlin-okhttp-jackson
          specgen: client-kotlin --jsonlib jackson --spec-file ./spec.yaml --generate-path .    
      - gen-client:
          path: clients/go
          specgen: client-go --spec-file ./spec.yaml --module-name test-client --generate-path .
      - gen-client:
          path: clients/ruby
          specgen: client-ruby --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/scala-sttp
          specgen: client-scala --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/ts-axios-superstruct
          specgen: client-ts --client axios --validation superstruct --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/ts-axios-iots
          specgen: client-ts --client axios --validation io-ts --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/ts-browser-fetch-superstruct
          specgen: client-ts --client browser-fetch --validation superstruct --spec-file ./spec.yaml --generate-path .
      - gen-client:
          path: clients/ts-node-fetch-iots
          specgen: client-ts --client node-fetch --validation io-ts --spec-file ./spec.yaml --generate-path .

      - gen-service:
          path: services/openapi
          specgen: openapi --spec-file ./spec.yaml --out-file ./swagger.yaml
      - gen-service:
          path: services/java-spring
          specgen: service-java --jsonlib jackson --spec-file ./spec.yaml --generate-path ./generated --services-path ./developed
      - gen-service:
          path: services/go
          specgen: service-go --spec-file ./spec.yaml --module-name test-service --generate-path ./generated --services-path ./developed
      - gen-service:
          path: services/scala-play
          specgen: service-scala --spec-file ./spec.yaml --generate-path ./generated --services-path ./developed
      - gen-service:
          path: services/ts-express-superstruct
          specgen: service-ts --server express --validation superstruct --spec-file ./spec.yaml --generate-path ./generated --services-path ./developed
      - gen-service:
          path: services/ts-koa-superstruct
          specgen: service-ts --server koa --validation superstruct --spec-file ./spec.yaml --generate-path ./generated --services-path ./developed

      - tree:
          path: ./models
      - tree:
          path: ./clients
      - tree:
          path: ./services

      - run:
          name: Commit changes
          command: |
            git add --all
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER
            git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/specgen-io/generated-code.git
            if [[ `git status --porcelain` ]]; then
              git commit -m "[skip ci] Generated code with specgen <<pipeline.parameters.specgen-version>>"
              git push
            else
              echo "No changes detected - nothing to commit"
            fi
            git tag -f -a v<<pipeline.parameters.specgen-version>> -m "Specgen verison: v<<pipeline.parameters.specgen-version>>"
            git push -f --tags

commands:
  gen-models:
    parameters:
      path:
        type: string
      specgen:
        type: string
    steps:
      - run:
          name: Download models spec
          command: |
            if [ ! -f /tmp/models/spec.yaml ]; then
              mkdir -p /tmp/models/
              cd /tmp/models/
              curl -LJO https://raw.githubusercontent.com/specgen-io/test-models/main/spec.yaml
            fi
      - run:
          name: Generate models code
          command: |
            mkdir -p <<parameters.path>>
            cd <<parameters.path>>
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen <<parameters.specgen>>
  gen-client:
    parameters:
      path:
        type: string
      specgen:
        type: string
    steps:
      - run:
          name: Download clients spec
          command: |
            if [ ! -f /tmp/clients/spec.yaml ]; then
              mkdir -p /tmp/clients/
              cd /tmp/clients/
              curl -LJO https://raw.githubusercontent.com/specgen-io/test-clients/main/spec.yaml
            fi
      - run:
          name: Generate client code
          command: |
            mkdir -p <<parameters.path>>
            cd <<parameters.path>>
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen <<parameters.specgen>>
  gen-service:
    parameters:
      path:
        type: string
      specgen:
        type: string
    steps:
      - run:
          name: Download service spec
          command: |
            if [ ! -f /tmp/services/spec.yaml ]; then
              mkdir -p /tmp/services/
              cd /tmp/services/
              curl -LJO https://raw.githubusercontent.com/specgen-io/test-services/main/spec.yaml
            fi
      - run:
          name: Generate service code
          command: |
            mkdir -p <<parameters.path>>
            cd <<parameters.path>>
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen <<parameters.specgen>>

  tree:
    parameters:
      path:
        type: string
        default: .
    steps:
      - run:
          name: Print flie system tree
          command: find <<parameters.path>> | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

workflows:
  generated-code:
    jobs:
      - generated-code:
          context: specgen
