version: 2.1

parameters:
  specgen-version:
    type: string
    default: 2.0.404

jobs:
  generate-commit:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - install-specgen
      - run:
          name: Generate code
          command: |
            find ./models | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
            ./specgen models-java --spec-file ./models/spec.yaml --generate-path ./models/java
            find ./models | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
            rm specgen
      - run:
          name: Commit changes
          command: |
            git config --global user.email "vladimir.sapronov@gmail.com"
            git config --global user.name "vsapronov"
            git status
            git add --all
            git status
            git commit -a -m "[skip ci] Generated code with specgen <<pipeline.parameters.specgen-version>>"
            git status

commands:
  install-specgen:
    parameters:
      command:
        type: string
        default: go test
    steps:
      - run:
          name: Install specgen
          command: |
            curl -L https://github.com/specgen-io/specgen/releases/download/v<<pipeline.parameters.specgen-version>>/specgen_linux_amd64.zip > specgen_linux_amd64.zip
            unzip -o specgen_linux_amd64.zip
            rm specgen_linux_amd64.zip

workflows:
  generate-commit:
    jobs:
      - generate-commit