version: 2.1

parameters:
  specgen-version:
    type: string
    default: 2.0.571
  specgen-version-major:
    type: string
    default: v2

jobs:
  generated-code:
    docker:
      - image: cimg/go:1.16.4
    steps:
      - checkout
      - run:
          name: Install specgen
          command: |
            go install github.com/specgen-io/specgen/<<pipeline.parameters.specgen-version-major>>@v<< pipeline.parameters.specgen-version >>
            specgen --help
      - run:
          name: Download models spec
          command: |
            mkdir -p /tmp/models/
            cd /tmp/models/
            curl -LJO https://raw.githubusercontent.com/specgen-io/test-models/main/spec.yaml
      - run:
          name: Download clients spec
          command: |
            mkdir -p /tmp/clients/
            cd /tmp/clients/
            curl -LJO https://raw.githubusercontent.com/specgen-io/test-clients/main/spec.yaml
      - run:
          name: Download services spec
          command: |
            mkdir -p /tmp/services/
            cd /tmp/services/
            curl -LJO https://raw.githubusercontent.com/specgen-io/test-services/main/spec.yaml
      - run:
          name: Generate models code
          command: |
            rm -R -- ./models/*/
            cd models

            mkdir openapi
            cd openapi
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen openapi --spec-file ./spec.yaml --out-file ./swagger.yaml

            mkdir java
            cd java
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-java --spec-file ./spec.yaml --generate-path .

            mkdir go
            cd go
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-go --spec-file ./spec.yaml --generate-path .

            mkdir ruby
            cd ruby
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-ruby --spec-file ./spec.yaml --generate-path .

            mkdir scala-circe
            cd scala-circe
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-scala-circe --spec-file ./spec.yaml --generate-path .

            mkdir ts-iots
            cd ts-iots
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-ts --validation io-ts --spec-file ./spec.yaml --generate-path .

            mkdir ts-superstruct
            cd ts-superstruct
            cp /tmp/models/spec.yaml ./spec.yaml
            specgen models-ts --validation superstruct --spec-file ./spec.yaml --generate-path .
      - tree:
          path: ./models
      - run:
          name: Generate clients code
          command: |
            rm -R -- ./clients/*/
            cd clients

            mkdir openapi
            cd openapi
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen openapi --spec-file ./spec.yaml --out-file ./swagger.yaml
            
            mkdir go
            cd go
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen client-go --spec-file ./spec.yaml --generate-path .
            
            mkdir ruby
            cd ruby
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen client-ruby --spec-file ./spec.yaml --generate-path .
            
            mkdir scala-sttp
            cd scala-sttp
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen client-scala-sttp --spec-file ./spec.yaml --generate-path .
            
            mkdir ts-axios-superstruct
            cd ts-axios-superstruct
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen client-ts-axios --validation superstruct --spec-file ./spec.yaml --generate-path .
            
            mkdir ts-axios-iots
            cd ts-axios-iots
            cp /tmp/clients/spec.yaml ./spec.yaml
            specgen client-ts-axios --validation io-ts --spec-file ./spec.yaml --generate-path .
      - tree:
          path: ./clients
      - run:
          name: Generate services code
          command: |
            rm -R -- ./services/*/
            cd services

            mkdir openapi
            cd openapi
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen openapi --spec-file ./spec.yaml --out-file ./swagger.yaml

            mkdir go
            cd go
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen service-go --spec-file ./spec.yaml --generate-path .

            mkdir scala-play
            cd scala-play
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen service-scala-play --spec-file ./spec.yaml --generate-path . --services-path ./services

            mkdir ts-express-superstruct
            cd ts-express-superstruct
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen service-ts --server express --validation superstruct --spec-file ./spec.yaml --generate-path . --services-path ./services

            mkdir ts-koa-superstruct
            cd ts-koa-superstruct
            cp /tmp/services/spec.yaml ./spec.yaml
            specgen service-ts --server koa --validation superstruct --spec-file ./spec.yaml --generate-path . --services-path ./services
      - tree:
          path: ./services
      - run:
          name: Commit changes
          command: |
            git add --all
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER
            git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/specgen-io/generated-code.git
            if [[ `git status --porcelain` ]]; then
              git commit -m "[skip ci] Generated code with specgen <<pipeline.parameters.specgen-version>>"
              git push
            else
              echo "No changes detected - nothing to commit"
            fi
            git tag -f -a v<<pipeline.parameters.specgen-version>> -m "Specgen verison: v<<pipeline.parameters.specgen-version>>"
            git push -f --tags

commands:
  tree:
    parameters:
      path:
        type: string
        default: .
    steps:
      - run:
          name: Print flie system tree
          command: find <<parameters.path>> | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

workflows:
  generated-code:
    jobs:
      - generated-code:
          context: specgen
